language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

#set environmet variables
env:
  - PYTHONPATH=$TRAVIS_BUILD_DIR/Quickspin

# command to run tests
script:
  - cd Quickspin/tests
  - python quickspin_tests.py
